ASSIGNMENT 1

In [3]:
import numpy as np
import pandas as pd

In [4]:
#1.
l=[" iphone-14 Pro ", "SAMSUNG galaxy   S23", "oneplus_11", "Pixel--7 Pro", " xiaomi 13 "]
data=np.array(l)
print(data, "\n", type(data))
ser=pd.Series(l)

[' iphone-14 Pro ' 'SAMSUNG galaxy   S23' 'oneplus_11' 'Pixel--7 Pro'
 ' xiaomi 13 '] 
 <class 'numpy.ndarray'>


In [5]:
def space_check(x):
    c=0
    for i in range(x):
        if not x[(i-1)].isspace() and x[i].isspace() and not x[(i+1)].isspace():
                c=c+1
        if c>2:
            return False
    return True
data2=ser.apply(lambda x:x.strip().replace('_',' ').replace('-',' ').title())
s1=ser[ser.apply(space_check)]
print(s1)

TypeError: 'str' object cannot be interpreted as an integer

In [77]:
def chk_pass(x):
    u=0
    l=0
    d=0
    sp=0
    rep={}
    prev=""
    c=1
    if (len(x)>=8):
        for i in range(len(x)):
            if x[i].isupper():
                u=u+1
            elif x[i].islower():
                l=l+1
            elif x[i].isdigit():
                d=d+1
            elif x[i] in '!@#$%^&*':
                sp=sp+1
            if x[i]==prev:
                c=c+1
                if c>3:
                    return "Weak"
            else:
                c=1
        if u>=1 and l>=1 and d>=1 and sp>=1:
            return "Strong"
        else:
            return "Moderate"
    return "Weak"
            
l=["Admin123!","weakpass","STRONGpass99@","12345678","User#2024Secure"]
for i in l:
    print(f"{i}: {chk_pass(i)}")

Admin123!: Strong
weakpass: Moderate
STRONGpass99@: Strong
12345678: Moderate
User#2024Secure: Strong


In [135]:
l=[" alice ", "BOB", "ChArLie"," david"]
ser1=pd.Series(l)
data3=ser1.apply(lambda x:x.strip().title())
data3.drop_duplicates()
data3

0      Alice
1        Bob
2    Charlie
3      David
dtype: object

In [127]:
arr=np.random.randint(1,100, size=(10, 10))
print(arr,"\n",arr.shape,"\n")
greater_than_50=arr[arr > 50]
arr[arr % 3 == 0]=-1

print("\nElements greater than 50\n", greater_than_50)
print("\nModified Array:\n", arr)
print("\nIndices of elements that are multiple of 7:\n", np.argwhere(arr%7 == 0))
print("\n3x3 subarray:\n",arr[3:6,3:6])

[[56 17 25 22 26 85 94  8 27 42]
 [ 3 95  8 54 13 54 36 71 78 48]
 [93 70 17 97 98 33 62 42 67 88]
 [35 68 29 40 35 51 72 73 89  3]
 [62 82 86 95 67  9 14  9 50  5]
 [33 47 43 13 34 12 41 27 58 22]
 [22  1 38 24 90 83 10  1 53 23]
 [93 98 58 78  8 24 43 99 60 57]
 [66 84 80 94 44  2 27 90 99 14]
 [46 25 32 12 34 67 98  7 87 30]] 
 (10, 10) 


Elements greater than 50
 [56 85 94 95 54 54 71 78 93 70 97 98 62 67 88 68 51 72 73 89 62 82 86 95
 67 58 90 83 53 93 98 58 78 99 60 57 66 84 80 94 90 99 67 98 87]

Modified Array:
 [[56 17 25 22 26 85 94  8 -1 -1]
 [-1 95  8 -1 13 -1 -1 71 -1 -1]
 [-1 70 17 97 98 -1 62 -1 67 88]
 [35 68 29 40 35 -1 -1 73 89 -1]
 [62 82 86 95 67 -1 14 -1 50  5]
 [-1 47 43 13 34 -1 41 -1 58 22]
 [22  1 38 -1 -1 83 10  1 53 23]
 [-1 98 58 -1  8 -1 43 -1 -1 -1]
 [-1 -1 80 94 44  2 -1 -1 -1 14]
 [46 25 32 -1 34 67 98  7 -1 -1]]

Indices of elements that are multiple of 7:
 [[0 0]
 [2 1]
 [2 4]
 [3 0]
 [3 4]
 [4 6]
 [7 1]
 [8 9]
 [9 6]
 [9 7]]

3x3 subarray:
 [[40 35 -

In [137]:
arr1=np.random.randint(20, size=(2,2))
arr2=np.random.randint(20, size=(2,2))
print(f"1st Array:\n{arr1}")
print(f"2nd Array:\n{arr2}")
print(f"Multiplication Array:\n{arr1@arr2}")

1st Array:
[[ 8 10]
 [ 8 10]]
2nd Array:
[[16 16]
 [ 5  6]]
Multiplication Array:
[[178 188]
 [178 188]]


In [139]:
ser4=pd.Series([1,2,3,4,5,9,11,13,15])
def prime_check(x):
    if x < 2:
        return False
    for i in range(2,int(x**0.5)+1):
        if x%i==0:
            return False
    return True
prime=ser4[ser4.apply(prime_check)]
prime

1     2
2     3
4     5
6    11
7    13
dtype: int64