ASSIGNMENT 1

In [3]:
import numpy as np
import pandas as pd

In [15]:
#1.
l=[" iphone-14 Pro ", "SAMSUNG galaxy S23", "oneplus_11", "Pixel--7 Pro", " xiaomi 13 "]
data=np.array(l)
print(data, "\n", type(data))
ser=pd.Series(l)

[' iphone-14 Pro ' 'SAMSUNG galaxy S23' 'oneplus_11' 'Pixel--7 Pro'
 ' xiaomi 13 '] 
 <class 'numpy.ndarray'>


In [45]:
data2=ser.apply(lambda x:x.strip().replace('_',' ').replace('-',' ').title().replace('  ',' '))
data2


0         Iphone 14 Pro
1    Samsung Galaxy S23
2            Oneplus 11
3           Pixel 7 Pro
4             Xiaomi 13
dtype: object

In [77]:
def chk_pass(x):
    u=0
    l=0
    d=0
    sp=0
    rep={}
    prev=""
    c=1
    if (len(x)>=8):
        for i in range(len(x)):
            if x[i].isupper():
                u=u+1
            elif x[i].islower():
                l=l+1
            elif x[i].isdigit():
                d=d+1
            elif x[i] in '!@#$%^&*':
                sp=sp+1
            if x[i]==prev:
                c=c+1
                if c>3:
                    return "Weak"
            else:
                c=1
        if u>=1 and l>=1 and d>=1 and sp>=1:
            return "Strong"
        else:
            return "Moderate"
    return "Weak"
            
l=["Admin123!","weakpass","STRONGpass99@","12345678","User#2024Secure"]
for i in l:
    print(f"{i}: {chk_pass(i)}")

Admin123!: Strong
weakpass: Moderate
STRONGpass99@: Strong
12345678: Moderate
User#2024Secure: Strong


In [71]:
l=[" alice ", "BOB", "ChArLie"," david"]
ser1=pd.Series(l)
data3=ser1.apply(lambda x:x.strip().title())
data3.drop_duplicates()
data3

0      Alice
1        Bob
2    Charlie
3      David
dtype: object

In [105]:
arr=np.random.randint(1,100, size=(10, 10))
print(arr,"\n",arr.shape,"\n")
greater_than_50=arr[arr > 50]
arr[arr % 3 == 0]=-1

print("\nElements greater than 50\n", greater_than_50)
print("\nModified Array:\n", arr)
print("\nIndices of elements that are multiple of 7:\n", np.argwhere(arr%7 == 0))
print("\n3x3 subarray:\n",arr[3:6,3:6])

[[39 29 77 84 80 59 76 72  6 84]
 [ 7 80 56 74 90 24 24 43 26 97]
 [95 97 30 25 48 54 74 27 20 41]
 [19 74 20 86 14 90 37 77 63 20]
 [17  5 17 66 23 83 63 97 20 33]
 [60 57  1 23 29 64 39 82 66 77]
 [76 65  2 65 38 77 46 44 53 49]
 [ 2  8 90  7 43 77 91 62 91 57]
 [57 88 11 62 60 28 70  2 88 44]
 [63 80 10 47 18 81 74 30 45 38]] 
 (10, 10) 


Elements greater than 50
 [77 84 80 59 76 72 84 80 56 74 90 97 95 97 54 74 74 86 90 77 63 66 83 63
 97 60 57 64 82 66 77 76 65 65 77 53 90 77 91 62 91 57 57 88 62 60 70 88
 63 80 81 74]

Modified Array:
 [[-1 29 77 -1 80 59 76 -1 -1 -1]
 [ 7 80 56 74 -1 -1 -1 43 26 97]
 [95 97 -1 25 -1 -1 74 -1 20 41]
 [19 74 20 86 14 -1 37 77 -1 20]
 [17  5 17 -1 23 83 -1 97 20 -1]
 [-1 -1  1 23 29 64 -1 82 -1 77]
 [76 65  2 65 38 77 46 44 53 49]
 [ 2  8 -1  7 43 77 91 62 91 -1]
 [-1 88 11 62 -1 28 70  2 88 44]
 [-1 80 10 47 -1 -1 74 -1 -1 38]]

Indices of elements that are multiple of 7:
 [[0 2]
 [1 0]
 [1 2]
 [3 4]
 [3 7]
 [5 9]
 [6 5]
 [6 9]
 [7 3]
 [7 5]
 [7 

In [107]:
arr1=np.random.randint(20, size=(2,2))
arr2=np.random.randint(20, size=(2,2))
print(f"1st Array:\n{arr1}")
print(f"2nd Array:\n{arr2}")
print(f"Multiplication Array:\n{arr1@arr2}")

1st Array:
[[ 3 14]
 [10  2]]
2nd Array:
[[18  8]
 [15  3]]
Multiplication Array:
[[264  66]
 [210  86]]


In [109]:
ser4=pd.Series([1,2,3,4,5,9,11,13,15])
def prime_check(x):
    if x < 2:
        return False
    for i in range(2,x**0.5):
        if x%i==0:
            return False
    return True
prime=ser4[ser4.apply(prime_check)]
prime

TypeError: 'float' object cannot be interpreted as an integer