SKILL ASSIGNMENT 1

In [2]:
import numpy as np
import pandas as pd

In [ ]:
"""
1.	Assume you have some messy product names as – 
" iphone-14 Pro ",
"SAMSUNG galaxy S23",
"oneplus_11",
"Pixel--7 Pro",
" xiaomi 13 "
Write Python code to do the following  – 
•	Make a 1-D representation of the given data 
•	Remove extra spaces
•	Replace _ and - with space
•	Convert to Title Case
•	Remove duplicate spaces
•	Output standardized product names
Use apply as and when require.
"""

In [23]:
l=[" iphone-14 Pro ", "SAMSUNG   galaxy S23", "oneplus_11", "Pixel--7 Pro", " xiaomi 13 "]
arr=pd.Series(l)
print(f"""Original data\n{arr}""")
def clean_product(name):
    name=name.replace('_', ' ')
    name=name.replace('-', ' ')
    name=name.strip()
    
    result=""
    for i in range(len(name)):
        if name[i]==' ' and name[i-1]== ' ':
            continue
        result+=name[i]
    name=result.title()
    return name            
x=arr.apply(clean_product)
print(x)

Original data
0          iphone-14 Pro 
1    SAMSUNG   galaxy S23
2              oneplus_11
3            Pixel--7 Pro
4              xiaomi 13 
dtype: object
0         Iphone 14 Pro
1    Samsung Galaxy S23
2            Oneplus 11
3           Pixel 7 Pro
4             Xiaomi 13
dtype: object


In [ ]:
"""
2.	Consider a data given as follows which represents password – 
    "Admin123!",
    "weakpass",
    "STRONGpass99@",
    "12345678",
    "User#2024Secure"
Write Python code  to check the following and return that the password is “Strong”, “Moderate” or “Weak”
•	At least 8 characters
•	At least 1 uppercase
•	At least 1 lowercase
•	At least 1 digit
•	At least 1 special character
•	No repeating character more than 3 times consecutively
"""

In [5]:
def chk_pass(x):
    u=0
    l=0
    d=0
    sp=0
    rep={}
    prev=""
    c=1
    if (len(x)>=8):
        for i in range(len(x)):
            if x[i].isupper():
                u=u+1
            elif x[i].islower():
                l=l+1
            elif x[i].isdigit():
                d=d+1
            elif x[i] in '!@#$%^&*':
                sp=sp+1
            if x[i]==prev:
                c=c+1
                if c>3:
                    return "Weak"
            else:
                c=1
        if u>=1 and l>=1 and d>=1 and sp>=1:
            return "Strong"
        else:
            return "Moderate"
    return "Weak"
            
l=["Admin123!","weakpass","STRONGpass99@","12345678","User#2024Secure"]
for i in l:
    print(f"{i}: {chk_pass(i)}")

Admin123!: Strong
weakpass: Moderate
STRONGpass99@: Strong
12345678: Moderate
User#2024Secure: Strong


In [ ]:
"""
3.	Create a Python series from the given list 
[" alice ", "BOB", "ChArLie", " david"]. Write python code using 
apply to Remove spaces, Convert to title case and Remove duplicates
(if any)."""

In [6]:
l=[" alice ", "BOB", "ChArLie"," david"]
ser1=pd.Series(l)
data3=ser1.apply(lambda x:x.strip().title())
data3.drop_duplicates()
data3

0      Alice
1        Bob
2    Charlie
3      David
dtype: object

In [ ]:
"""
4.	Write python code to create a numpy array of  size 10x10 randomly 
generated in between 1 to 100. Then extract all elements has higher
value than 50 and replace all elements divisible by 3 with -1. Find the 
indices of all elements that are multiples of 7 and Finally extract a 3x3 
subarray from the center. 
"""

In [7]:
arr=np.random.randint(1,100, size=(10, 10))
print(arr,"\n",arr.shape,"\n")
greater_than_50=arr[arr > 50]
arr[arr % 3 == 0]=-1

print("\nElements greater than 50\n", greater_than_50)
print("\nModified Array:\n", arr)
print("\nIndices of elements that are multiple of 7:\n", np.argwhere(arr%7 == 0))
print("\n3x3 subarray:\n",arr[3:6,3:6])

[[12 18 35 55 43 90 72 22 89 11]
 [49 29 10 86 44 74  6 22 54 23]
 [46 73 51 53 63 95 80 57 82 36]
 [12 99 20 23 62  4  2 90 88 27]
 [48 22 41  7 27 47 94 71 84 91]
 [57 35 79 14 15 98 44  8 60 74]
 [69 33 69  5 36 77 83 49 12 16]
 [48 59 29 47 74 64 28 52 63 55]
 [86 92 49 12 18  6  4 78 64 63]
 [24 87 99  7 12 84 19 98  1 12]] 
 (10, 10) 


Elements greater than 50
 [55 90 72 89 86 74 54 73 51 53 63 95 80 57 82 99 62 90 88 94 71 84 91 57
 79 98 60 74 69 69 77 83 59 74 64 52 63 55 86 92 78 64 63 87 99 84 98]

Modified Array:
 [[-1 -1 35 55 43 -1 -1 22 89 11]
 [49 29 10 86 44 74 -1 22 -1 23]
 [46 73 -1 53 -1 95 80 -1 82 -1]
 [-1 -1 20 23 62  4  2 -1 88 -1]
 [-1 22 41  7 -1 47 94 71 -1 91]
 [-1 35 79 14 -1 98 44  8 -1 74]
 [-1 -1 -1  5 -1 77 83 49 -1 16]
 [-1 59 29 47 74 64 28 52 -1 55]
 [86 92 49 -1 -1 -1  4 -1 64 -1]
 [-1 -1 -1  7 -1 -1 19 98  1 -1]]

Indices of elements that are multiple of 7:
 [[0 2]
 [1 0]
 [4 3]
 [4 9]
 [5 1]
 [5 3]
 [5 5]
 [6 5]
 [6 7]
 [7 6]
 [8 2]
 [9 3]
 [9 7]

In [ ]:
"""
5.	Write a python code to multiply two 2-D array without any 
predefined function. """

In [27]:
arr1_rows=int(input("Number of rows in 1st matrix: "))
arr1_cols=int(input("Number of columns in 1st matrix: "))
arr2_rows=int(input("Number of rows in 2nd matrix: "))
arr2_cols=int(input("Number of columns in 2nd matrix: "))
while True:
    if arr1_cols != arr2_rows:   
        print("No. of columns of 1st matrix must be equal to no. of rows of 2nd matrix")
        arr2_rows = int(input("Re-enter number of rows in 2nd matrix: "))  
    else:
        break
arr1=np.random.randint(20, size=(arr1_rows,arr1_cols))
arr2=np.random.randint(20, size=(arr2_rows,arr2_cols))
print(f"1st Array:\n{arr1}")
print(f"2nd Array:\n{arr2}")
#print(f"Multiplication Array:\n{arr1@arr2}")
print("Matrix multiplication\n")
arr_res=np.zeros((arr1_rows,arr2_cols), dtype=int)
m=len(arr1)
n=len(arr1[0])
p=len(arr2[0])
for i in range(m):
    for j in range(p):
        for k in range(n):
            arr_res[i][j]+=arr1[i][k] * arr2[k][j]
for i in arr_res:
    print(i)

Number of rows in 1st matrix:  3
Number of columns in 1st matrix:  4
Number of rows in 2nd matrix:  3
Number of columns in 2nd matrix:  4


No. of columns of 1st matrix must be equal to no. of rows of 2nd matrix


Re-enter number of rows in 2nd matrix:  4


1st Array:
[[ 9 17  6 18]
 [ 3 16  9 12]
 [ 8  6  6 10]]
2nd Array:
[[ 7 13 13 11]
 [ 6  8 19  4]
 [ 3  5  7  8]
 [15 18  7  1]]
Matrix multiplication

[453 607 608 233]
[324 428 490 181]
[260 362 330 170]


In [ ]:
"""6.	Write a python program to extract the prime numbers from a
given series.
"""

In [22]:
import math
def isprime(x):
    if x==2:
        return True
    if x<2:
        return False
    for i in range(2, int(math.sqrt(x)+1)):
        if x%i==0:
            return False
    return True
    
l=[1,2,3,4,5,6,17,19]
ser1=pd.Series(l)
prime=ser1.apply(isprime)
for i in range(len(l)):
    print(f"{l[i]}-> {prime[i]}")

1-> False
2-> True
3-> True
4-> False
5-> True
6-> False
17-> True
19-> True
