In [2]:
import numpy as np
myArr=np.array([1,2,'hello',4])
print(myArr, type(myArr))
print(myArr.dtype)

['1' '2' 'hello' '4'] <class 'numpy.ndarray'>
<U11


In [17]:
arr=np.array([3,6, 32, 7], np.int32)   #fixing the datatype of array
print(arr, type(arr), arr.dtype)
print(arr.shape)          #rowxcoln , length
print(arr.size)

[ 3  6 32  7] <class 'numpy.ndarray'> int32
(4,)
4


In [13]:
arr=np.array([
    [3,4,5,6],
    [1,2,3,4]
])
print(arr, type(arr), arr.dtype)
print(arr.shape)

[[3 4 5 6]
 [1 2 3 4]] <class 'numpy.ndarray'> int32
(2, 4)


In [18]:
#array creation: conversion from other python ds like list
l=[
    [1, 'harry', 3],
    [5, 85, 7],
    [9, 67.2, 125.578]
]
listArr=np.array(l)      #converting lists to array using typecasting
print(listArr, type(listArr), listArr.dtype)
print(listArr.shape[0])
print(listArr.size)       #number of elements in array

[['1' 'harry' '3']
 ['5' '85' '7']
 ['9' '67.2' '125.578']] <class 'numpy.ndarray'> <U32
3
9


In [20]:
zeroarr=np.zeros((2, 5))
print(zeroarr, type(zeroarr), zeroarr.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'> float64


In [22]:
rng=np.arange(15)
print(rng, rng.shape)
reshape=rng.reshape(3,5)
print(reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
lspace=np.linspace(1,5, 10) #10 equally spaced nos b2m 1 to 5
print(lspace, type(lspace), lspace.shape, lspace.dtype)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ] <class 'numpy.ndarray'> (10,) float64


In [26]:
empty=np.empty((4,6))
print(empty, type(empty), empty.dtype)

[[2.41907520e-312 1.29441743e-312 1.93101617e-312 9.33678148e-313
  9.33678148e-313 1.08221785e-312]
 [9.33678148e-313 1.16709769e-312 9.33678148e-313 2.33419537e-312
  9.76118064e-313 2.33419537e-312]
 [1.08221785e-312 8.70018275e-313 2.37663529e-312 2.22809558e-312
  2.46151512e-312 2.05833592e-312]
 [2.41907520e-312 2.12199579e-312 2.56761491e-312 2.14321575e-312
  1.29060870e-306 8.34424766e-308]] <class 'numpy.ndarray'> float64


In [30]:
empty=np.empty_like(lspace)
print(empty)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [31]:
ide=np.identity(5)
print(ide, ide.size, ide.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 25 (5, 5)


In [32]:
ide=np.eye(5)
print(ide, ide.size, ide.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 25 (5, 5)


In [48]:
x=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr=np.array(x)
print(arr, arr.shape)
print("Row elements addition: ", arr.sum(axis=0))
print("Columns elements addition: ", arr.sum(axis=1))
print("Transpose addition: \n", arr.T)
print(f"Sum of only 1 row: {arr[0].sum(axis=0)}")
#print(f"Sum of only 1 column: {arr[0].sum()}")
print(f"Trace: {np.trace(arr)}")
print(f"Determinant: {np.linalg.det(arr)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
Row elements addition:  [12 15 18]
Columns elements addition:  [ 6 15 24]
Transpose addition: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of only 1 row: 6
Trace: 15
Determinant: -9.51619735392994e-16


In [49]:
arr_flat=arr.flatten()
print(f"The flattened array is {arr_flat}")

The flattened array is [1 2 3 4 5 6 7 8 9]


In [51]:
for i in arr_flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [52]:
print(arr.ravel())

[1 2 3 4 5 6 7 8 9]


In [60]:
one=np.ones((5,2))
print(one)
one1=np.array([1,64,4,634,2])
print(f"index that contains the maximum-valued element={one1.argmax()}")
print(f"index that contains the minimum-valued element={one1.argmin()}")
print(f"Sorted array element positions:{np.argsort(one1)}")  #array of indices

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
index that contains the maximum-valued element=3
index that contains the minimum-valued element=0
Sorted array element positions:[0 4 2 1 3]


In [61]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
print(arr.argmax())    #we get the indices
print(arr.argmax(axis=0))

8
[2 2 2]


In [66]:
arr1=arr.copy()
print(arr1)
print(arr+arr1)
print(arr*arr1)
print(np.dot(arr,arr1))
print(arr-arr1)
print(np.matmul(arr, arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [67]:
print(np.where(arr1>5))

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [68]:
print(np.linalg.inv(arr))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [70]:
import pandas as pd
d={
    "name":["A", "B", "C", "D"],
    "marks":[30, 40, 50, 60],
    "city":["AB", "BC","CD", "DA"]
}
df=pd.DataFrame(d)
print(df)

  name  marks city
0    A     30   AB
1    B     40   BC
2    C     50   CD
3    D     60   DA


In [72]:
df.to_csv('avengers.csv')
mycsv=pd.read_csv('avengers.csv')
print(mycsv,"\n", type(mycsv))
print(mycsv['name'])

   Unnamed: 0 name  marks city
0           0    A     30   AB
1           1    B     40   BC
2           2    C     50   CD
3           3    D     60   DA 
 <class 'pandas.core.frame.DataFrame'>
0    A
1    B
2    C
3    D
Name: name, dtype: object


In [75]:
mycsv['marks'][2]=99
print(mycsv)
df.head(3)

   Unnamed: 0 name  marks city
0           0    A     30   AB
1           1    B     40   BC
2           2    C     99   CD
3           3    D     60   DA


C:\Users\shama\AppData\Local\Temp\ipykernel_23412\757120282.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mycsv['marks'][2]=99
C:\Users\shama\AppData\Local\Temp\ipykernel_23412\757120282.py:1: SettingWithCopyWarning: 
A value is trying

,name,marks,city
0,A,30,AB
1,B,40,BC
2,C,50,CD


In [74]:
mycsv.index=['first', 'second', 'third', 'fourth', 'fifth']
print(mycsv)

ValueError: Length mismatch: Expected axis has 4 elements, new values have 5 elements

In [83]:
new_df=pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(new_df)

            0         1         2         3         4
0    0.687634  0.787980  0.884225  0.842407  0.823815
1    0.200717  0.511522  0.939224  0.197302  0.427219
2    0.492083  0.234258  0.454210  0.725633  0.672358
3    0.866303  0.645071  0.299334  0.708276  0.313393
4    0.117946  0.915149  0.881053  0.765783  0.575352
..        ...       ...       ...       ...       ...
329  0.734596  0.270322  0.626928  0.365660  0.299642
330  0.383535  0.494212  0.038676  0.185935  0.784998
331  0.676254  0.005732  0.614322  0.686247  0.535278
332  0.836545  0.901762  0.807872  0.763384  0.709326
333  0.637063  0.541621  0.618466  0.912814  0.898390

[334 rows x 5 columns]


In [79]:
new_def.describe()


NameError: name 'new_def' is not defined

In [80]:
new_df.sort_index()

,0,1,2,3,4
0,0.535955,0.753682,0.469517,0.282069,0.161083
1,0.702568,0.616182,0.462547,0.057730,0.478073
2,0.624593,0.117112,0.272568,0.846281,0.139018
3,0.404246,0.195393,0.317233,0.383668,0.096317
4,0.374923,0.052745,0.012865,0.696191,0.502965
...,...,...,...,...,...
329,0.620611,0.473685,0.131181,0.556934,0.329327
330,0.416555,0.690818,0.004754,0.109354,0.589488
331,0.013733,0.506900,0.939312,0.835454,0.771635
332,0.953196,0.401934,0.894559,0.001149,0.626446


In [81]:
new=new_df.copy()
new[1][3]=8765
print(new)

            0            1         2         3         4
0    0.535955     0.753682  0.469517  0.282069  0.161083
1    0.702568     0.616182  0.462547  0.057730  0.478073
2    0.624593     0.117112  0.272568  0.846281  0.139018
3    0.404246  8765.000000  0.317233  0.383668  0.096317
4    0.374923     0.052745  0.012865  0.696191  0.502965
..        ...          ...       ...       ...       ...
329  0.620611     0.473685  0.131181  0.556934  0.329327
330  0.416555     0.690818  0.004754  0.109354  0.589488
331  0.013733     0.506900  0.939312  0.835454  0.771635
332  0.953196     0.401934  0.894559  0.001149  0.626446
333  0.777257     0.916372  0.068980  0.996202  0.019295

[334 rows x 5 columns]


C:\Users\shama\AppData\Local\Temp\ipykernel_23412\476385193.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new[1][3]=8765


In [87]:
print(new_df.loc[1:5])

          0         1         2         3         4
1  0.200717  0.511522  0.939224  0.197302  0.427219
2  0.492083  0.234258  0.454210  0.725633  0.672358
3  0.866303  0.645071  0.299334  0.708276  0.313393
4  0.117946  0.915149  0.881053  0.765783  0.575352
5  0.434016  0.266564  0.523832  0.403027  0.874654


In [89]:
print(new_df.loc[:,3])

0      0.842407
1      0.197302
2      0.725633
3      0.708276
4      0.765783
         ...   
329    0.365660
330    0.185935
331    0.686247
332    0.763384
333    0.912814
Name: 3, Length: 334, dtype: float64


In [90]:
new_df.loc[0,4]=664
new_df.head()

,0,1,2,3,4
0,0.687634,0.787980,0.884225,0.842407,664.000000
1,0.200717,0.511522,0.939224,0.197302,0.427219
2,0.492083,0.234258,0.454210,0.725633,0.672358
3,0.866303,0.645071,0.299334,0.708276,0.313393
4,0.117946,0.915149,0.881053,0.765783,0.575352


In [91]:
new_df.drop(1, axis=1, inplace=True)
new_df.head()

,0,2,3,4
0,0.687634,0.884225,0.842407,664.000000
1,0.200717,0.939224,0.197302,0.427219
2,0.492083,0.454210,0.725633,0.672358
3,0.866303,0.299334,0.708276,0.313393
4,0.117946,0.881053,0.765783,0.575352


In [92]:
new_df.columns=["A","B","C","D"]

In [93]:
new_df

,A,B,C,D
0,0.687634,0.884225,0.842407,664.000000
1,0.200717,0.939224,0.197302,0.427219
2,0.492083,0.454210,0.725633,0.672358
3,0.866303,0.299334,0.708276,0.313393
4,0.117946,0.881053,0.765783,0.575352
...,...,...,...,...
329,0.734596,0.626928,0.365660,0.299642
330,0.383535,0.038676,0.185935,0.784998
331,0.676254,0.614322,0.686247,0.535278
332,0.836545,0.807872,0.763384,0.709326


In [94]:
new_df.reset_index(drop=True, inplace=True)
new_df.head()

,A,B,C,D
0,0.687634,0.884225,0.842407,664.000000
1,0.200717,0.939224,0.197302,0.427219
2,0.492083,0.454210,0.725633,0.672358
3,0.866303,0.299334,0.708276,0.313393
4,0.117946,0.881053,0.765783,0.575352


In [95]:
new_df.describe()

,A,B,C,D
count,334.000000,334.000000,334.000000,334.000000
mean,0.496120,0.499044,0.496234,2.474166
std,0.285031,0.295033,0.290748,36.306820
min,0.004942,0.005836,0.007680,0.000894
25%,0.250984,0.236569,0.225915,0.276267
50%,0.476422,0.490737,0.506494,0.475535
75%,0.728376,0.749577,0.752929,0.713572
max,0.998401,0.998991,0.997667,664.000000
