In [4]:
import numpy as np
import pandas as pd

In [ ]:
"""
1.	Assume you have some messy product names as – 
" iphone-14 Pro ",
"SAMSUNG galaxy S23",
"oneplus_11",
"Pixel--7 Pro",
" xiaomi 13 "
Write Python code to do the following  – 
•	Make a 1-D representation of the given data 
•	Remove extra spaces
•	Replace _ and - with space
•	Convert to Title Case
•	Remove duplicate spaces
•	Output standardized product names
Use apply as and when require.
"""

In [12]:
l=[" iphone-14 Pro ", "SAMSUNG   galaxy S23", "oneplus_11", "Pixel--7 Pro", " xiaomi 13 "]
arr=pd.Series(l)
print("Original data\n",arr,"\n")
def clean_product(name):
    name=name.replace('_', ' ')
    name=name.replace('-', ' ')
    name=name.strip()
    
    result=""
    for i in range(len(name)):
        if name[i]==' ' and name[i-1]== ' ':
            continue
        result+=name[i]
    name=result.title()
    return name            
x=arr.apply(clean_product)
print(x)

Original data
 0          iphone-14 Pro 
1    SAMSUNG   galaxy S23
2              oneplus_11
3            Pixel--7 Pro
4              xiaomi 13 
dtype: object 

0         Iphone 14 Pro
1    Samsung Galaxy S23
2            Oneplus 11
3           Pixel 7 Pro
4             Xiaomi 13
dtype: object


In [ ]:
"""
2.	Consider a data given as follows which represents password – 
    "Admin123!",
    "weakpass",
    "STRONGpass99@",
    "12345678",
    "User#2024Secure"
Write Python code  to check the following and return that the password is “Strong”, “Moderate” or “Weak”
•	At least 8 characters
•	At least 1 uppercase
•	At least 1 lowercase
•	At least 1 digit
•	At least 1 special character
•	No repeating character more than 3 times consecutively
"""

In [21]:
def password(key):
    nu=0
    nl=0
    nd=0
    nsp=0
    c=1
    prev=""
    if len(key)>=8:
        for i in range(len(key)):
            if key[i]==prev:
                c+=1
                if c>3:
                    return "Weak"
            else:
                c=1
            if key[i].isupper():
                nu+=1
            elif key[i].islower():
                nl+=1
            elif key[i].isdigit():
                nd+=1
            elif key[i] in '!@#$%^&':
                nsp+=1
        if nu>=1 and nl>=1 and nd>=1 and nsp>=1:
                return "Strong"
        else:
                return "Moderate"
    return "Weak"
x=["Admin123!",
    "weakpass",
    "STRONGpass99@",
    "12345678",
    "User#2024Secure"]
for i in x:
    print(f"{i}: {password(i)}")

Admin123!: Strong
weakpass: Moderate
STRONGpass99@: Strong
12345678: Moderate
User#2024Secure: Strong


In [ ]:
"""
3.	Create a Python series from the given list 
[" alice ", "BOB", "ChArLie", " david"]. Write python code using 
apply to Remove spaces, Convert to title case and Remove duplicates
(if any)."""

In [22]:
l=[" alice ", "BOB", "ChArLie", " david"]
ser=pd.Series(l)
print("Original data\n", ser,"\n")
ser_clean=ser.apply(lambda x:x.strip().title())
print(ser_clean)

Original data
 0     alice 
1        BOB
2    ChArLie
3      david
dtype: object 

0      Alice
1        Bob
2    Charlie
3      David
dtype: object


In [ ]:
"""
4.	Write python code to create a numpy array of  size 10x10 randomly 
generated in between 1 to 100. Then extract all elements has higher
value than 50 and replace all elements divisible by 3 with -1. Find the 
indices of all elements that are multiples of 7 and Finally extract a 3x3 
subarray from the center. 
"""

In [29]:
arr=np.random.randint(1,100,size=(10, 10))
print("Original Array\n",arr,"\n")
greater_than_50=arr[arr>50]
arr[arr%3==0]=-1
print("Elements greater than 50\n", greater_than_50)
print("\nElements divisible by 3 with -1\n", arr)
print("\nIndices of elements multiples of 7:\n", np.argwhere(arr%7==0))
print("\n3x3 subarray:\n",arr[3:6,3:6])


Original Array
 [[77  4 17 25 85 41 76 52 70 50]
 [ 6 71 34 99 60 65 55 94 91 80]
 [95 74 45 29 59 31 11 15 85 12]
 [45  4 65 97 13 17  2 56 11  1]
 [ 4 89 78 82 28 84 74 79 66 13]
 [92 60 52 32 61 67 58 13 37 90]
 [74  6 49 70 86 13 76 23 30 10]
 [ 2 93 57 65 73 86 90 49 82 60]
 [62  7 46 84 80 88 63 40 31 97]
 [58 91 62 99 28 83  2 79 28 17]] 

Elements greater than 50
 [77 85 76 52 70 71 99 60 65 55 94 91 80 95 74 59 85 65 97 56 89 78 82 84
 74 79 66 92 60 52 61 67 58 90 74 70 86 76 93 57 65 73 86 90 82 60 62 84
 80 88 63 97 58 91 62 99 83 79]

Elements divisible by 3 with -1
 [[77  4 17 25 85 41 76 52 70 50]
 [-1 71 34 -1 -1 65 55 94 91 80]
 [95 74 -1 29 59 31 11 -1 85 -1]
 [-1  4 65 97 13 17  2 56 11  1]
 [ 4 89 -1 82 28 -1 74 79 -1 13]
 [92 -1 52 32 61 67 58 13 37 -1]
 [74 -1 49 70 86 13 76 23 -1 10]
 [ 2 -1 -1 65 73 86 -1 49 82 -1]
 [62  7 46 -1 80 88 -1 40 31 97]
 [58 91 62 -1 28 83  2 79 28 17]]

Indices of elements multiples of 7:
 [[0 0]
 [0 8]
 [1 8]
 [3 7]
 [4 4]
 [6 2]
 [

In [ ]:
"""
5.	Write a python code to multiply two 2-D array without any 
predefined function. """

In [32]:
A=[
    [2,1],
    [1,2]
]
B=[
    [3,2],
    [2,3]
]
A_arr=np.array(A)
B_arr=np.array(B)
print("Matrix multiplication:\n", A_arr@B_arr)

Matrix multiplication:
 [[8 7]
 [7 8]]


In [ ]:
"""6.	Write a python program to extract the prime numbers from a
given series.
"""

In [39]:
import math
def isprime(x):
    if x==2:
        return True
    if x<2:
        return False
    for i in range(2, int(math.sqrt(x)+1)):
        if x%i==0:
            return False
    return True
l=[1,2,3,4,5,6,17,19]
ser1=pd.Series(l)
prime=ser1.apply(isprime)
for i in range(len(l)):
    print(f"{l[i]}, {prime[i]}")

1, False
2, True
3, True
4, False
5, True
6, False
17, True
19, True
