In [1]:
from scipy import stats
import math

In [11]:
lambda_rate = 25 # no of customer returns in a retail per day at a rate of 25returns per day
prob_le_30=stats.poisson.cdf(30, lambda_rate)  #probability that the number of returns less than 30 in a day
prob_gt_30=1 - prob_le_30                      #probability that the number of returns exceeds 30 in a day
print(f"Probability that the number of returns exceeds 30 in a day {prob_gt_30:<.4f}")

fraudulent_ret=0.05
new_lambda_rate = lambda_rate * fraudulent_ret
prob_le_1f= stats.poisson.cdf(1, new_lambda_rate)
prob_le_2f=1-prob_le_1f
print(f"Probability that there will be atleast 2 fraudulant returns in any given day: {prob_le_2f :<.4f}")

Probability that the number of returns exceeds 30 in a day 0.1367
Probability that there will be atleast 2 fraudulant returns in any given day: 0.3554


In [20]:
total_applied = 8
prob_selected = 0.42     #probability of getting selected is constant and independent
prob_le_3u = stats.binom.cdf(2,8,0.42)
prob_ge_3u=1-prob_le_3u
print(f"Probability of getting a call from at least 3 universities {prob_ge_3u:<.4f}")

prob_e_4u = stats.binom.pmf(4,8,0.42)
print(f"Probability of getting a call from exactly 4 universities {prob_e_4u:<.4f}")

Probability of getting a call from at least 3 universities 0.7250
Probability of getting a call from exactly 4 universities 0.2465


In [25]:
hours=85                #mean time between failures
prob_le_85 = stats.expon.cdf(85, loc=1/85, scale=85)
print(f"Probability that the system will fail before 85hrs {prob_le_85 :<.4f}")

prob_upto_150 = 1 - stats.expon.cdf(150, loc=1/85, scale=85)
print(f"Probability that the system will not fail upto 150hrs {prob_upto_150 :<.4f}")

Probability that the system will fail before 85hrs 0.6321
Probability that the system will not fail upto 150hrs 0.1713


In [27]:
no_of_farmers=1000
land_size=10
avg_pesticide_spray=38
std_dev=5

def z_sc(sample_mean, avg_pesticide_spray, std_dev):
    z_score=(sample_mean - avg_pesticide_spray)/(std_dev)
    return z_score
z_score_gt_50=z_sc(50, avg_pesticide_spray, std_dev)
if z_score_gt_50 < 1.64:
    #Null Hypothesis preserved
    prob = stats.norm.cdf(z_score_gt_50)
else:
    #Alternative Hypothesis used
    prob = 1 - stats.norm.cdf(z_score_gt_50)
print(f"Proportion of farmers is spraying more than 50li of pesticide in a week = {prob :<.4f}")

z_score_lt_10=z_sc(10, avg_pesticide_spray, std_dev)
if z_score_lt_10 < -1.64:
    #Null Hypothesis preserved
    prob_10 = stats.norm.cdf(z_score_lt_10)
else:
    #Alternative Hypothesis used
    prob_10 = 1 - stats.norm.cdf(z_score_lt_10)
print(f"Proportion of farmers is spraying less than 10li of pesticide in a week = {round(prob_10)}")

#30<Z<60
z_score_gt_30=z_sc(30, avg_pesticide_spray, std_dev)
if z_score_lt_10 < -1.64:
    #Null Hypothesis preserved
    prob_30 = stats.norm.cdf(z_score_gt_30)
else:
    #Alternative Hypothesis used
    prob_30 = 1 - stats.norm.cdf(z_score_gt_30)

z_score_lt_60=z_sc(60, avg_pesticide_spray, std_dev)
if z_score_lt_60 > 1.64:
    #Null Hypothesis preserved
    prob_60 = stats.norm.cdf(z_score_lt_60)
else:
    #Alternative Hypothesis used
    prob_60 = 1 - stats.norm.cdf(z_score_lt_60)
print(f"Proportion of farmers is spraying between 30li and 60li of pesticide in a week = {prob_60 - prob_30 :<.4f}")

Proportion of farmers is spraying more than 50li of pesticide in a week = 0.0082
Proportion of farmers is spraying less than 10li of pesticide in a week = 0
Proportion of farmers is spraying between 30li and 60li of pesticide in a week = 0.9452


In [7]:
import numpy as np

arr1=np.arange(2,19,2)
arr1=arr1.reshape(3,3)
arr2=np.arange(1,18,2)
arr2=arr2.reshape(3,3)
print(f"{arr1}\n\n{arr2}\n")
assert arr1.shape[0]==arr2.shape[1]
arr3 = np.zeros((arr1.shape[0], arr2.shape[1]), dtype=int)
for i in range(arr1.shape[0]):
    for j in range(arr2.shape[1]):
        total=0
        for k in range(arr1.shape[0]):
            total += arr1[i,k] * arr2[k,j]
        arr3[i,j]=total
print(arr3.astype(int))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

[[108 132 156]
 [234 294 354]
 [360 456 552]]


In [10]:
arr1=np.arange(2,19,2)
arr1=arr1.reshape(3,3)
arr2=np.arange(1,18,2)
arr2=arr2.reshape(3,3)
print(np.matmul(arr1,arr2))

[[108 132 156]
 [234 294 354]
 [360 456 552]]
