N-DIMENSIONAL ARRAYS

In [9]:
import numpy as np
l=[
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
]
arr=np.array(l)
print(arr,"\n", type(arr), "\n", arr.dtype, "\n", arr.size, "\n", arr.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 
 <class 'numpy.ndarray'> 
 int64 
 12 
 (4, 3)


In [13]:
print(arr[2,2])

5


In [15]:
t=(
    (1,2,3),
    (2,3,4),
    (4,5,6)
)
arrt=np.array(t)
print(arrt,"\n", type(arrt), "\n", arrt.dtype, "\n", arrt.size, "\n", arrt.shape)

[[1 2 3]
 [2 3 4]
 [4 5 6]] 
 <class 'numpy.ndarray'> 
 int64 
 9 
 (3, 3)


In [19]:
B=arr.reshape(6,2)
print(arr)
print(B, B.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[1 2]
 [3 2]
 [3 4]
 [3 4]
 [5 4]
 [5 6]] (6, 2)


In [27]:
multizeros=np.zeros((5,3), dtype=int)
print(multizeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
multiones=np.ones((3,5), dtype=int)
print(multiones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [35]:
fullarr=np.full((3,5), np.inf)
print(fullarr)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [47]:
iden=np.eye(3,4, dtype=int)
print(iden)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [65]:
A=np.arange(1,11)
B=np.split(A,5)
As=np.array_split(A,4)
print(B)
print(B[0])
print(B[0][0])
print(As)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[1 2]
1
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [71]:
arr=np.random.randint(1,100,10)
even=arr[arr%2==0]
add=np.sum(even)
mean=np.mean(even)
print(f"Original array: {arr}")
print(f"Even nos. : {even}")
print(f"sum of all elements: {add}")
print(f"mean of all elements: {mean:<.2f}")

Original array: [74 58  7 99 70 24 62 69 17 23]
Even nos. : [74 58 70 24 62]
sum of all elements: 288
mean of all elements: 57.60


In [83]:
A=np.random.randint(100, size=(4,5))
print(A)
print(f"sum of all elements: {A.sum()}")
print(f"sum of column-wise elements: {A.sum(axis=0)}")
print(f"sum of row-wise elements: {A.sum(axis=1)}")

[[49 48  7 16 42]
 [24 68 97 30 98]
 [35 59 11 32 55]
 [11 41 83  6 34]]
sum of all elements: 846
sum of column-wise elements: [119 216 198  84 229]
sum of row-wise elements: [162 317 192 175]


In [89]:
A=np.random.randint(100, size=(2,3,5,6))
print(A)
print(f"sum when axis =0: {A.sum(axis=0)}")
print(f"sum when axis =1: {A.sum(axis=1)}")
print(f"sum when axis =2: {A.sum(axis=2)}")
print(f"sum when axis =3: {A.sum(axis=3)}")

print(f"sum when axis =-1: {A.sum(axis=-1)}")
print(f"max when axis =0: {A.max(axis=0)}")
print(f"min when axis =1: {A.min(axis=1)}")

[[[[53 40  6 56 32 91]
   [88 10 50 71 71 23]
   [71 59 27  5 72 89]
   [36 28 28 76 95 38]
   [96 52  7 52 89 45]]

  [[50 81 50 67  0 66]
   [56 76 24 41 69 53]
   [83 79 29 77 31  1]
   [49 30 42 80 74 45]
   [40  4 28  9 22 52]]

  [[80  2 20 81 44 54]
   [11 48 72 64 59  5]
   [38 86  9 87 29 48]
   [ 3 28 23 66 39 48]
   [ 0 91 70 87 13 14]]]


 [[[ 6 65 63 72 45 39]
   [90 17 58 92 88 25]
   [68 89 82 66 98 77]
   [68  7 61 88 95 66]
   [76 17  9 65 72 58]]

  [[23 79 72 99 95 15]
   [21 34 51 89  4  8]
   [26 51 92 55 70  1]
   [74 48 39 58 63 10]
   [35 83 89 20 54 77]]

  [[27 65 97 54  4 12]
   [86 57 93 94 83 95]
   [41 47 28 30 95 51]
   [87 65 30 29  6  1]
   [97 80  4 79  6 42]]]]
sum when axis =0: [[[ 59 105  69 128  77 130]
  [178  27 108 163 159  48]
  [139 148 109  71 170 166]
  [104  35  89 164 190 104]
  [172  69  16 117 161 103]]

 [[ 73 160 122 166  95  81]
  [ 77 110  75 130  73  61]
  [109 130 121 132 101   2]
  [123  78  81 138 137  55]
  [ 75  87 117  29  76 

In [97]:
A=np.random.randint(10, size=(2,3))
B=np.random.randint(10, size=(2,3))
S=A+B
D=A-B
M=A*B
#at=A@B
print(A)
print(B)
print(f"sum={S}")
print(f"diff={D}")
print(f"product={M}")
#print(f"matrix multiplication={at}")


[[6 2 9]
 [5 8 0]]
[[6 6 8]
 [6 5 7]]
sum=[[12  8 17]
 [11 13  7]]
diff=[[ 0 -4  1]
 [-1  3 -7]]
product=[[36 12 72]
 [30 40  0]]


In [101]:
A=np.random.randint(10, size=(2,3))
B=np.random.randint(10, size=(3,2))
at=A@B
print(f"matrix multiplication=\n{at}")

matrix multiplication=
[[42 48]
 [43 38]]


In [105]:
A=np.random.randint(10, size=(2,3))
B=np.random.randint(10, size=(3,2))
at=A@B
E=np.matmul(A,B)
print(A)
print(B)
print(at)
print(E)


[[5 5 4]
 [1 3 9]]
[[6 3]
 [2 6]
 [0 2]]
[[40 53]
 [12 39]]
[[40 53]
 [12 39]]


In [113]:
l1=[
    [1,2],
    [2,3]
]
l2=[
    [2,3],
    [3,4]
]
C=np.matmul(l1,l2)
dot=np.dot(l1, l2)
# @ doesnt work with lists
print(f"matrix multiplication:\n{C}")
print(f"dot product:\n{dot}")


matrix multiplication:
[[ 8 11]
 [13 18]]
dot product:
[[ 8 11]
 [13 18]]


In [125]:
#input 2 matrices from user (3x3) find sum and product
l1=[]
l2=[]
for i in range(9):
    x=int(input(f"enter element{i+1}:"))
    l1.append(x)
A1=np.array(l1)
B1=np.split(A1,3)
print("-----1st Matrix----")
print(B1)
for i in range(9):
    x=int(input(f"enter element{i+1}:"))
    l2.append(x)
A2=np.array(l2)
B2=np.split(A2,3)
print("-----2nd Matrix----")
print(B2)
add=B1+B2
mul=np.matmul(B1, B2)
print(f"Sum of 2 matrices: {add}")
print(f"Product of 2 matrices: {mul}")

enter element1: 1
enter element2: 2
enter element3: 3
enter element4: 4
enter element5: 5
enter element6: 6
enter element7: 7
enter element8: 8
enter element9: 9


-----1st Matrix----
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


enter element1: 9
enter element2: 8
enter element3: 7
enter element4: 6
enter element5: 5
enter element6: 4
enter element7: 3
enter element8: 3
enter element9: 2


-----2nd Matrix----
[array([9, 8, 7]), array([6, 5, 4]), array([3, 3, 2])]
Sum of 2 matrices: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([9, 8, 7]), array([6, 5, 4]), array([3, 3, 2])]
Product of 2 matrices: [[ 30  27  21]
 [ 84  75  60]
 [138 123  99]]
