NUMPY : Array is an object of class numpy.ndarray, cannot initialise array as a=[1 2 3 4], will show error

In [2]:
import numpy as np
l=[1,2,3,4,5]
t=(1,2,3,4,5)
A=np.array(l)
B=np.array(t)
print(A, type(A))
print(f"shape, size of array1: {A.shape}, {A.size}")
print(B, type(B))
print(f"shape of array2: {B.shape}")

[1 2 3 4 5] <class 'numpy.ndarray'>
shape, size of array1: (5,), 5
[1 2 3 4 5] <class 'numpy.ndarray'>
shape of array2: (5,)


In [4]:
print(A[4])

5


In [6]:
zeroarrf=np.zeros(5)
zeroarr=np.zeros(5, np.int32)
zeroarr1=np.zeros(5, dtype=int)
print(zeroarrf, zeroarrf.dtype)
print(zeroarr, zeroarr.dtype)
print(zeroarr1, zeroarr1.dtype)

[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32
[0 0 0 0 0] int64


In [8]:
onesarrf=np.ones(5)
onesarr=np.ones(5, np.int32)
onesarr1=np.ones(5, dtype=int)
print(onesarrf, onesarrf.dtype)
print(onesarr, onesarr.dtype)
print(onesarr1, onesarr1.dtype)

[1. 1. 1. 1. 1.] float64
[1 1 1 1 1] int32
[1 1 1 1 1] int64


In [10]:
#np.arange(x, y): including x but excluding y
Arange=np.arange(50, 60, 2)     # (start, stop, step)
print(Arange)

[50 52 54 56 58]


In [12]:
#linspace decides the step by itself, but step for arange must be defined by user
linspacef=np.linspace(3,7,10,endpoint=False)
linspacet=np.linspace(3,7,10,endpoint=True)
print(linspacef)
print(linspacet)

[3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6]
[3.         3.44444444 3.88888889 4.33333333 4.77777778 5.22222222
 5.66666667 6.11111111 6.55555556 7.        ]


In [14]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr1=arr
arr1

array([1, 3, 5, 7, 9])

In [18]:
arr[0]=20
arr

array([20,  3,  5,  7,  9])

In [20]:
arr1

array([20,  3,  5,  7,  9])

In [22]:
#this is because, 1 ndarray object has 2 aliases : arr and arr1

In [24]:
arr2=np.copy(arr)
print(f"Original array: {arr}")
print(f"Copied array: {arr2}")

Original array: [20  3  5  7  9]
Copied array: [20  3  5  7  9]


In [26]:
arr[0]=10
print(f"Original array: {arr}")
print(f"Copied array: {arr2}")

Original array: [10  3  5  7  9]
Copied array: [20  3  5  7  9]


In [28]:
arr=arr*2
arr

array([20,  6, 10, 14, 18])

In [30]:
#define an array A containing odd nos 1-10, B containing even nos 1-10
A=np.arange(1,10,2)
B=np.arange(2,11,2)
print(f"ODD NO. ARRAY: {A}")
print(f"EVEN NO. ARRAY: {B}")

ODD NO. ARRAY: [1 3 5 7 9]
EVEN NO. ARRAY: [ 2  4  6  8 10]


In [32]:


C=A+B
print(f"Addition of A and B: {C}")

Addition of A and B: [ 3  7 11 15 19]


In [34]:

M=np.dot(A,B)
print(M)

190


In [36]:
new=np.arange(1,11)
print(new)
print(f"sum: {new.sum(axis=0)}")
print(f"mean: {new.mean(axis=0)}")
print(f"max: {new.max(axis=0)}")
print(f"min: {new.min(axis=0)}")

[ 1  2  3  4  5  6  7  8  9 10]
sum: 55
mean: 5.5
max: 10
min: 1


In [38]:
print(f"Average: {np.average(new)}")   # average is a function of numpy library but sum, max, min, mean are member methods of class ndarray
#unlike mean, average() can be used to calculate weighted average
w=[2,1,2,1,2,1,2,1,2,1]
print(f"Average using weights: {np.average(new, weights=w):<.2f}")

Average: 5.5
Average using weights: 5.33


In [40]:
A=np.arange(1,10,2)
print(A)
B=np.arange(2,11,2)
print(B)
print(f"Median of nos 1 to 10 odd nos: {np.median(A)}")
print(f"Median of nos 1 to 10 even nos: {np.median(B)}")

[1 3 5 7 9]
[ 2  4  6  8 10]
Median of nos 1 to 10 odd nos: 5.0
Median of nos 1 to 10 even nos: 6.0


In [42]:
print(f"Standard Deviation of nos 1 to 10 odd nos: {np.std(A):<.2f}")
print(f"Varience of nos 1 to 10 odd nos: {np.var(A)}")
print(f"Standard Deviation of nos 1 to 10 even nos: {np.std(B):<.2f}")
print(f"Varience of nos 1 to 10 even nos: {np.var(B)}")

Standard Deviation of nos 1 to 10 odd nos: 2.83
Varience of nos 1 to 10 odd nos: 8.0
Standard Deviation of nos 1 to 10 even nos: 2.83
Varience of nos 1 to 10 even nos: 8.0


In [44]:
#np.sort():in-place sorting, no new object is created, by default quick_sort
unsorted=np.array([2,3,6,5,8,7,0])
sorted_arr=np.sort(unsorted, kind='heapsort')
print(f"Original array : {unsorted}")
print(f"Sorted array   : {sorted_arr}")

Original array : [2 3 6 5 8 7 0]
Sorted array   : [0 2 3 5 6 7 8]


In [46]:
#slicing : access elements based on index
#filtering : access elements based on values
slicing=np.arange(1,11)
Z=slicing[::6]
print(Z)

[1 7]


In [48]:
n=int(input("Enter number of elements in array: "))
l=[]
for i in range(n):
    x=int(input("Enter element: "))
    l.append(x)
array=np.array(l)
print(f"Array is: {array}")

Enter number of elements in array:  5
Enter element:  2
Enter element:  7
Enter element:  1
Enter element:  8
Enter element:  5


Array is: [2 7 1 8 5]


In [50]:
reverse=array[::-1]
print(f"reversed array:{reverse}")

reversed array:[5 8 1 7 2]


In [64]:
#filtering
arr1=np.arange(1,11)
print(arr1)
B=arr1[arr1%3==0]
print(B)

[ 1  2  3  4  5  6  7  8  9 10]
[3 6 9]


In [72]:
ran=np.random.randint(1,100,size=10)
print(ran)
divf=ran[ran%5==0]
print(divf)

[ 6 59 24 16 50 35 19 69 53 85]
[50 35 85]
