N-DIMENSIONAL ARRAYS

In [1]:
import numpy as np
l=[
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
]
arr=np.array(l)
print(arr,"\n", type(arr), "\n", arr.dtype, "\n", arr.size, "\n", arr.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 
 <class 'numpy.ndarray'> 
 int32 
 12 
 (4, 3)


In [2]:
print(arr[2,2])

5


In [3]:
t=(
    (1,2,3),
    (2,3,4),
    (4,5,6)
)
arrt=np.array(t)
print(arrt,"\n", type(arrt), "\n", arrt.dtype, "\n", arrt.size, "\n", arrt.shape)

[[1 2 3]
 [2 3 4]
 [4 5 6]] 
 <class 'numpy.ndarray'> 
 int32 
 9 
 (3, 3)


In [4]:
B=arr.reshape(6,2)
print(arr)
print(B, B.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[1 2]
 [3 2]
 [3 4]
 [3 4]
 [5 4]
 [5 6]] (6, 2)


In [5]:
multizeros=np.zeros((5,3), dtype=int)
print(multizeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
multiones=np.ones((3,5), dtype=int)
print(multiones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
fullarr=np.full((3,5), np.inf)
print(fullarr)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [8]:
iden=np.eye(3,4, dtype=int)
print(iden)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [9]:
A=np.arange(1,11)
B=np.split(A,5)
As=np.array_split(A,4)
print(B)
print(B[0])
print(B[0][0])
print(As)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[1 2]
1
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [10]:
arr=np.random.randint(1,100,10)
even=arr[arr%2==0]
add=np.sum(even)
mean=np.mean(even)
print(f"Original array: {arr}")
print(f"Even nos. : {even}")
print(f"sum of all elements: {add}")
print(f"mean of all elements: {mean:<.2f}")

Original array: [39 33 66 52 68 58 94 19 25 24]
Even nos. : [66 52 68 58 94 24]
sum of all elements: 362
mean of all elements: 60.33


In [11]:
A=np.random.randint(100, size=(4,5))
print(A)
print(f"sum of all elements: {A.sum()}")
print(f"sum of column-wise elements: {A.sum(axis=0)}")
print(f"sum of row-wise elements: {A.sum(axis=1)}")

[[88  1 17 66 40]
 [43 73 82 30 40]
 [ 4 53 25 35 53]
 [54  9 70 70 98]]
sum of all elements: 951
sum of column-wise elements: [189 136 194 201 231]
sum of row-wise elements: [212 268 170 301]


In [12]:
A=np.random.randint(100, size=(2,3,5,6))
print(A)
print(f"sum when axis =0: {A.sum(axis=0)}")
print(f"sum when axis =1: {A.sum(axis=1)}")
print(f"sum when axis =2: {A.sum(axis=2)}")
print(f"sum when axis =3: {A.sum(axis=3)}")

print(f"sum when axis =-1: {A.sum(axis=-1)}")
print(f"max when axis =0: {A.max(axis=0)}")
print(f"min when axis =1: {A.min(axis=1)}")

[[[[68 19 57  0 70 51]
   [85 96 96 92  1 50]
   [56 57 43 21 15 52]
   [88 93 10 25 82 16]
   [47 26 96 12 94 11]]

  [[98  7 69 32 30 58]
   [48 70 90 76 75 37]
   [32 83 37 41 65 96]
   [65 42 51 20 42 49]
   [ 4 54 91 12 84 60]]

  [[36 35 87 39 46 62]
   [65 98 35 21 45 53]
   [27 65 14 61 20 44]
   [17 76  9 92 57 78]
   [54 99 91 82 49 88]]]


 [[[65 46 79 12 37 30]
   [63 86 47 22 33 95]
   [94 95 44 91 91 42]
   [70 63  8 35 74 76]
   [53 59 91  8 15 99]]

  [[82 48 39 44 45 31]
   [ 8 36 45 47 31 47]
   [75 72 36 15 14 38]
   [43 56 81 16 97 76]
   [23 36 59 23 65 28]]

  [[21 42  2 16 84 73]
   [18 90  6 40 86 61]
   [ 7 53 67 48 97 38]
   [97 52 30 99 58 19]
   [77 43 43 95 84 38]]]]
sum when axis =0: [[[133  65 136  12 107  81]
  [148 182 143 114  34 145]
  [150 152  87 112 106  94]
  [158 156  18  60 156  92]
  [100  85 187  20 109 110]]

 [[180  55 108  76  75  89]
  [ 56 106 135 123 106  84]
  [107 155  73  56  79 134]
  [108  98 132  36 139 125]
  [ 27  90 150  35 149 

In [13]:
A=np.random.randint(10, size=(2,3))
B=np.random.randint(10, size=(2,3))
S=A+B
D=A-B
M=A*B
#at=A@B
print(A)
print(B)
print(f"sum={S}")
print(f"diff={D}")
print(f"product={M}")
#print(f"matrix multiplication={at}")


[[5 7 8]
 [1 1 3]]
[[4 7 8]
 [7 4 6]]
sum=[[ 9 14 16]
 [ 8  5  9]]
diff=[[ 1  0  0]
 [-6 -3 -3]]
product=[[20 49 64]
 [ 7  4 18]]


In [14]:
A=np.random.randint(10, size=(2,3))
B=np.random.randint(10, size=(3,2))
at=A@B
print(f"matrix multiplication=\n{at}")

matrix multiplication=
[[ 0 40]
 [28 92]]


In [15]:
A=np.random.randint(10, size=(2,3))
B=np.random.randint(10, size=(3,2))
at=A@B
E=np.matmul(A,B)
print(A)
print(B)
print(at)
print(E)


[[5 8 1]
 [6 4 9]]
[[1 7]
 [6 8]
 [6 9]]
[[ 59 108]
 [ 84 155]]
[[ 59 108]
 [ 84 155]]


In [16]:
l1=[
    [1,2],
    [2,3]
]
l2=[
    [2,3],
    [3,4]
]
C=np.matmul(l1,l2)
dot=np.dot(l1, l2)
# @ doesnt work with lists
print(f"matrix multiplication:\n{C}")
print(f"dot product:\n{dot}")


matrix multiplication:
[[ 8 11]
 [13 18]]
dot product:
[[ 8 11]
 [13 18]]


In [19]:
#input 2 matrices from user (3x3) find sum and product
l1=[]
l2=[]
for i in range(9):
    x=int(input(f"enter element{i+1}:"))
    l1.append(x)
A1=np.array(l1)
B1=np.reshape(A1, (3,3))
print("-----1st Matrix----")
print(B1)
for i in range(9):
    x=int(input(f"enter element{i+1}:"))
    l2.append(x)
A2=np.array(l2)
B2=np.reshape(A2, (3,3))
print("-----2nd Matrix----")
print(B2)
add=B1+B2
mul=np.matmul(B1, B2)
print(f"Sum of 2 matrices:\n {add}")
print(f"Product of 2 matrices:\n {mul}")

enter element1: 1
enter element2: 2
enter element3: 3
enter element4: 4
enter element5: 5
enter element6: 6
enter element7: 7
enter element8: 8
enter element9: 9


-----1st Matrix----
[[1 2 3]
 [4 5 6]
 [7 8 9]]


enter element1: 1
enter element2: 2
enter element3: 3
enter element4: 4
enter element5: 5
enter element6: 6
enter element7: 7
enter element8: 89
enter element9: 7


-----2nd Matrix----
[[ 1  2  3]
 [ 4  5  6]
 [ 7 89  7]]
Sum of 2 matrices:
 [[ 2  4  6]
 [ 8 10 12]
 [14 97 16]]
Product of 2 matrices:
 [[ 30 279  36]
 [ 66 567  84]
 [102 855 132]]
